4

diff --git a/.github/workflows/auto-pull.yml b/.github/workflows/auto-pull.yml
--- a/.github/workflows/auto-pull.yml
+++ b/.github/workflows/auto-pull.yml
@@ -39,18 +39,18 @@ jobs:
           branchName=$(echo "$GITHUB_REF" | awk -F/ '{print $3}')
           
           while read -r line; do
-            # Extract the host and ansible_user from each line in the inventory.ini
+            # Extract the host and user from each line in the inventory.ini
             host=$(echo "$line" | grep -oP '^[a-zA-Z0-9.-]+')
-            ansible_user=$(echo "$line" | grep -oP 'ansible_user=\K\w+')
-            echo "Connecting to $ansible_user@$host"
+            user=$(echo "$line" | grep -oP 'user=\K\w+')
+            echo "Connecting to $user@$host"
             if [ -n "$unresolvedHost" ] && grep -q "$host" unresolved_hosts.txt; then
-              echo "Skipping $ansible_user@$host due to unresolved host"
+              echo "Skipping $user@$host due to unresolved host"
               continue
             fi
 
             # Attempt SSH connection and execute commands
-            ssh -o "StrictHostKeyChecking=no" "$ansible_user@$host" "
-              echo 'Connected to $ansible_user@$host'
+            ssh -o "StrictHostKeyChecking=no" "$user@$host" "
+              echo 'Connected to $user@$host'
               cd /Ansible &&
               git stash --include-untracked &&
               currentBranchName=\$(git rev-parse --abbrev-ref HEAD) &&
@@ -60,7 +60,7 @@ jobs:
               git reset --hard origin/$branchName &&
               git checkout \$currentBranchName &&
               git stash pop
-            " || echo "Error: Could not update code on $ansible_user@$host" &
+            " || echo "Error: Could not update code on $user@$host" &
 
           done < <(grep -E '^[^\[#;]' inventory.ini)
           wait
