handle ssh failure#6

diff --git a/.github/workflows/auto-pull.yml b/.github/workflows/auto-pull.yml
--- a/.github/workflows/auto-pull.yml
+++ b/.github/workflows/auto-pull.yml
@@ -20,11 +20,14 @@ jobs:
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+
           # Extract IPs from the inventory file and add them to known_hosts with error handling
           for host in $(grep -Eo '^[^#;]+(\.[^#;]+)(com|net)' inventory); do
             echo "Adding $host to known_hosts"
-            ssh-keyscan -H $host >> ~/.ssh/known_hosts 2>/dev/null || echo "Warning: $host is unreachable or failed to add to known_hosts"
-            unresolvedHost=$host
+            ssh-keyscan -H $host >> ~/.ssh/known_hosts 2>/dev/null || {
+              echo "Warning: $host is unreachable or failed to add to known_hosts"
+              echo "$host" >> unresolved_hosts.txt
+            }
           done
 
       - name: Pull Latest Code on Servers
@@ -32,8 +35,11 @@ jobs:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         run: |
           # shellcheck disable=SC2095
-            echo "unresolvedHost: $unresolvedHost"
+          unresolvedHost=$(cat unresolved_hosts.txt || echo "No unresolved hosts")
+
+          echo "Unresolved Hosts: $unresolvedHost"
           branchName=$(echo "$GITHUB_REF" | awk -F/ '{print $3}')
+          
           while read -r line; do
             # Extract the host and ansible_user from each line in the inventory
             host=$(echo "$line" | grep -Eo '^[^#;]+(\.[^#;]+)(com|net)')
@@ -57,4 +63,3 @@ jobs:
           done < <(grep -E '^[^\[#;]' inventory)
           wait
           echo "Code pull process completed on all servers"
-      
